version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: anime-sqlserver
    environment:
      SA_PASSWORD: "@Password2025PRO"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - anime-network
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: ProjetoAnime/Dockerfile
    container_name: anime-api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=AnimeDB;User=sa;Password=@Password2025PRO;
    networks:
      - anime-network

volumes:
  sqlvolume:

networks:
  anime-network:
